// src/briefs/briefLogo.ts

import type { BriefDefinition } from '../types';

const briefLogo: BriefDefinition = {
  id: 'logo',
  i18n: {
    title: {
      ru: 'Дизайн Лого',
      en: 'Logo Design',
      ua: 'Дизайн логотипу',
    },
    labels: {
      ru: {
        projectTitle: 'Название проекта (для сохранения)',
        companyName: 'Название компании:',
        industry: 'Сфера деятельности:',
        audience: 'Целевая аудитория:',
        uniqueness: 'Уникальность:',
        associations: 'Ассоциации для логотипа:',
        style: 'Желаемый стиль логотипа:',
        brand: 'Фирменные цвета и элементы:',
        formatLogo: 'Формат логотипа:',
        wishes: 'Ваши пожелания:',
        refs: 'Примеры логотипов:',
        budget: 'Бюджет и сроки:',
        extras: 'Нужно ли что-то ещё?',
        other: 'Другое:',
      },
      en: {
        projectTitle: 'Project Title (for saving)',
        companyName: 'Company name:',
        industry: 'Industry / field:',
        audience: 'Target audience:',
        uniqueness: 'Uniqueness / differentiators:',
        associations: 'Logo associations (feelings/traits):',
        style: 'Preferred logo style:',
        brand: 'Brand colors & elements:',
        formatLogo: 'Logo format:',
        wishes: 'Your wishes / must-have & must-not:',
        refs: 'Logo references:',
        budget: 'Budget & deadline:',
        extras: 'Anything else needed?',
        other: 'Other:',
      },
      ua: {
        projectTitle: 'Назва проєкту (для збереження)',
        companyName: 'Назва компанії:',
        industry: 'Сфера діяльності:',
        audience: 'Цільова аудиторія:',
        uniqueness: 'Унікальність:',
        associations: 'Асоціації для логотипу:',
        style: 'Бажаний стиль логотипа:',
        brand: 'Фірмові кольори та елементи:',
        formatLogo: 'Формат логотипа:',
        wishes: 'Ваші побажання:',
        refs: 'Приклади логотипів:',
        budget: 'Бюджет і терміни:',
        extras: 'Потрібно ще щось?',
        other: 'Інше:',
      },
    },
    placeholders: {
      ru: {
        projectTitle_ph: 'Введите название проекта',
        companyName_ph: 'Ваш бренд или название компании',
        industry_ph: 'Чем вы занимаетесь (доставка, косметика, юриспруденция и т.д.)',
        audience_ph: 'Кто ваш клиент? Возраст, пол, регион, интересы',
        uniqueness_ph: 'Что вас отличает (скорость, качество, сервис, технологии и т.д.)',
        associations_ph: 'Какие эмоции должен вызывать логотип (премиум, современный, мягкий, надёжный и т.д.)',
        style_ph: 'Прикрепите или опишите стили, которые вам нравятся',
        brand_ph: 'Цвета, шрифты, элементы айдентики (если есть)',
        formatLogo_ph: 'Горизонтальный, вертикальный, иконка и т.п.',
        wishes_ph: 'Что обязательно/чего точно не должно быть',
        refs_ph: 'Ссылки/изображения логотипов, которые нравятся',
        budget_ph: 'Ваш бюджет и когда нужен логотип',
        extras_ph: 'Например: логобук, брендбук, фирменный стиль (опишите нужное или оставьте пустым)',
        other_ph: 'Любая дополнительная информация',
        /** ⬇️ путь к картинке-подсказке */
        formatLogo_help_img: '/logo-format.png'
      },
      en: {
        projectTitle_ph: 'Enter project title',
        companyName_ph: 'Your brand or company name',
        industry_ph: 'What you do (delivery, cosmetics, law, design, etc.)',
        audience_ph: 'Who is your client? Age, gender, region, interests',
        uniqueness_ph: 'What makes you different (speed, quality, service, tech, etc.)',
        associations_ph: 'Feelings the logo should convey (premium, modern, soft, reliable, etc.)',
        style_ph: 'Attach or describe styles you like',
        brand_ph: 'Brand colors, fonts, design elements (if any)',
        formatLogo_ph: 'Horizontal, vertical, icon, etc.',
        wishes_ph: 'Must-have and must-avoid',
        refs_ph: 'Links/images of logos you like',
        budget_ph: 'Your budget and target deadline',
        extras_ph: 'E.g., logobook, brandbook, corporate identity (describe what you need)',
        other_ph: 'Any additional info',
        /** ⬇️ image hint path */
        formatLogo_help_img: '/logo-format.png'
      },
      ua: {
        projectTitle_ph: 'Введіть назву проєкту',
        companyName_ph: 'Ваш бренд або назва компанії',
        industry_ph: 'Чим ви займаєтесь (доставка, косметика, право, дизайн тощо)',
        audience_ph: 'Хто ваш клієнт? Вік, стать, регіон, інтереси',
        uniqueness_ph: 'Що вас вирізняє (швидкість, якість, сервіс, технології тощо)',
        associations_ph: 'Які відчуття має викликати логотип (преміум, сучасний, м’який, надійний тощо)',
        style_ph: 'Додайте або опишіть стилі, які вам подобаються',
        brand_ph: 'Фірмові кольори, шрифти, елементи (за наявності)',
        formatLogo_ph: 'Горизонтальний, вертикальний, іконка тощо',
        wishes_ph: 'Що обов’язково/чого не повинно бути',
        refs_ph: 'Посилання/зображення логотипів, що подобаються',
        budget_ph: 'Ваш бюджет і коли потрібен логотип',
        extras_ph: 'Напр.: логобук, брендбук, фірмовий стиль (опишіть, що потрібно)',
        other_ph: 'Будь-яка додаткова інформація',
        /** ⬇️ шлях до зображення-підказки */
        formatLogo_help_img: '/logo-format.png'
      },
    },
  },
  fields: [
    { id: 'projectTitle', type: 'text',     labelKey: 'projectTitle', placeholderKey: 'projectTitle_ph', required: true },
    { id: 'companyName',  type: 'text',     labelKey: 'companyName',  placeholderKey: 'companyName_ph' },
    { id: 'industry',     type: 'text',     labelKey: 'industry',     placeholderKey: 'industry_ph' },
    { id: 'audience',     type: 'textarea', labelKey: 'audience',     placeholderKey: 'audience_ph' },
    { id: 'uniqueness',   type: 'textarea', labelKey: 'uniqueness',   placeholderKey: 'uniqueness_ph' },
    { id: 'associations', type: 'textarea', labelKey: 'associations', placeholderKey: 'associations_ph' },
    { id: 'style',        type: 'textarea', labelKey: 'style',        placeholderKey: 'style_ph' },
    { id: 'brand',        type: 'textarea', labelKey: 'brand',        placeholderKey: 'brand_ph' },

    { id: 'formatLogo',   type: 'text',     labelKey: 'formatLogo',   placeholderKey: 'formatLogo_ph', helpImageKey: 'formatLogo_help_img' },

    { id: 'wishes',       type: 'textarea', labelKey: 'wishes',       placeholderKey: 'wishes_ph' },
    { id: 'refs',         type: 'textarea', labelKey: 'refs',         placeholderKey: 'refs_ph' },
    { id: 'budget',       type: 'text',     labelKey: 'budget',       placeholderKey: 'budget_ph' },
    { id: 'extras',       type: 'textarea', labelKey: 'extras',       placeholderKey: 'extras_ph' },
    { id: 'other',        type: 'textarea', labelKey: 'other',        placeholderKey: 'other_ph' },
  ],
};

export default briefLogo;
