import type { BriefDefinition } from '../types';

const briefVideo: BriefDefinition = {
  id: 'video',
  i18n: {
    title: {
      ru: 'Моушн / Видео',
      en: 'Motion & Video Design',
      ua: 'Моушн / відео',
    },
    labels: {
      ru: {
        projectTitle: 'Название проекта (для сохранения)',
        about: '1. Кратко о проекте:',
        brand: '2. Информация о фирменном стиле:',
        links: '3. Сайт и ссылки на соцсети:',
        refs: '4. Референсы:',
        assets: '5. Материалы (видео/фото):',
        specs: '6. Количество, длительность и формат:',
        theses: '7. Рекламные сообщения/тезисы:',
        goals: '8. Цели проекта:',
        audience: '9. Целевая аудитория/идеальный клиент:',
        wishes: '10. Ваши предпочтения:',
        deadline: '11. Желаемый срок:',
      },
      en: {
        projectTitle: 'Project Title (for saving)',
        about: '1. Briefly about the project:',
        brand: '2. Brand identity information:',
        links: '3. Website and social media links:',
        refs: '4. References:',
        assets: '5. Links to materials (video/photo):',
        specs: '6. Required number, duration, and format:',
        theses: '7. Advertising messages/theses:',
        goals: '8. Project goals:',
        audience: '9. Target audience / ideal client:',
        wishes: '10. Your preferences:',
        deadline: '11. Desired deadline:',
      },
      ua: {
        projectTitle: 'Назва проєкту (для збереження)',
        about: '1. Коротко про проєкт:',
        brand: '2. Інформація про фірмовий стиль:',
        links: '3. Сайт та посилання на соцмережі:',
        refs: '4. Референси:',
        assets: '5. Матеріали (відео/фото):',
        specs: '6. Кількість, тривалість і формат:',
        theses: '7. Рекламні повідомлення/тези:',
        goals: '8. Цілі проєкту:',
        audience: '9. Цільова аудиторія/ідеальний клієнт:',
        wishes: '10. Ваші вподобання:',
        deadline: '11. Бажаний термін:',
      }
    },
    placeholders: {
      ru: {
        projectTitle_ph: 'Введите название проекта',
        about_ph: 'Опишите компанию, сферу деятельности и позиционирование (название, ниша, ценовой сегмент).',
        brand_ph: 'Брендбук, фирменные цвета, шрифты или правила айдентики. Если нет — можно ли выбрать на своё усмотрение?',
        links_ph: 'Ссылки на сайт и соцсети для примеров и понимания коммуникации.',
        refs_ph: 'Ссылки на креативы/рекламу/аккаунты, которые нравятся, и почему они актуальны.',
        assets_ph: 'Ссылки на видео, фото и прочие материалы. Если чего-то нет — что можно найти и использовать на наше усмотрение.',
        specs_ph: 'Сколько видео, какая длительность и форматы (напр.: сторис/рилс, 9:16, 1:1).',
        theses_ph: 'Ключевые тексты/идеи: заголовок, основное сообщение, CTA.\nПример:\nvideo1 — 5–10 сек — (Текст)\nvideo2 — 0–3 сек — (Текст)\nvideo3 — 7–12 сек — (Текст)',
        goals_ph: 'Главная цель: продажи, трафик, узнаваемость, промо события и т.д.',
        audience_ph: 'Кто аудитория: кто это, возраст, пол, доход, какие проблемы/нужды решает продукт.',
        wishes_ph: 'Что обязательно должно быть или чего точно избегать в видео.',
        deadline_ph: 'Когда нужен готовый результат.',
      },
      en: {
        projectTitle_ph: 'Enter project title',
        about_ph: 'Describe your company, activity, and market positioning (name, niche, price segment).',
        brand_ph: 'Brand guidelines, colors, fonts, or identity rules. If unavailable—can we choose at our discretion?',
        links_ph: 'Links to website and social media for reference.',
        refs_ph: 'Links to creatives/ads/accounts you like and why they are relevant.',
        assets_ph: 'Links to videos, photos, or other assets. If anything is missing—what can we source and use at our discretion.',
        specs_ph: 'How many videos, their duration, and formats (e.g., story/reel, 9:16, 1:1).',
        theses_ph: 'Key texts/ideas: headline, main info, CTA.\nExample:\nvideo1 – 5–10 sec – (Text)\nvideo2 – 0–3 sec – (Text)\nvideo3 – 7–12 sec – (Text)',
        goals_ph: 'Main goal: sales, traffic, brand awareness, event promotion, etc.',
        audience_ph: 'Who is the audience: age, gender, income, pains/needs your product solves.',
        wishes_ph: 'What you definitely want to include or avoid in the video.',
        deadline_ph: 'When the final deliverable is needed.',
      },
      ua: {
        projectTitle_ph: 'Введіть назву проєкту',
        about_ph: 'Опишіть компанію, сферу діяльності та позиціонування (назва, ніша, ціновий сегмент).',
        brand_ph: 'Брендбук, фірмові кольори, шрифти або правила айдентики. Якщо немає — чи можемо обрати на власний розсуд?',
        links_ph: 'Посилання на сайт і соцмережі для прикладу.',
        refs_ph: 'Посилання на креативи/рекламу/акаунти, що подобаються, і чому вони актуальні.',
        assets_ph: 'Посилання на відео, фото та інші матеріали. Якщо чогось бракує — що можна знайти й використати на наш розсуд.',
        specs_ph: 'Скільки відео, яка тривалість і формати (напр.: сторіс/рілс, 9:16, 1:1).',
        theses_ph: 'Ключові тексти/ідеї: заголовок, основне повідомлення, CTA.\nПриклад:\nvideo1 — 5–10 с — (Текст)\nvideo2 — 0–3 с — (Текст)\nvideo3 — 7–12 с — (Текст)',
        goals_ph: 'Головна мета: продажі, трафік, впізнаваність, промо події тощо.',
        audience_ph: 'Хто аудиторія: хто це, вік, стать, дохід, які потреби/проблеми вирішує продукт.',
        wishes_ph: 'Що обов’язково має бути або чого слід уникати у відео.',
        deadline_ph: 'Коли потрібен готовий результат.',
      }
    }
  },
  fields: [
    { id: 'projectTitle', type: 'text',     labelKey: 'projectTitle', placeholderKey: 'projectTitle_ph', required: true },
    { id: 'about',        type: 'textarea', labelKey: 'about',        placeholderKey: 'about_ph' },
    { id: 'brand',        type: 'textarea', labelKey: 'brand',        placeholderKey: 'brand_ph' },
    { id: 'links',        type: 'textarea', labelKey: 'links',        placeholderKey: 'links_ph' },
    { id: 'refs',         type: 'textarea', labelKey: 'refs',         placeholderKey: 'refs_ph' },
    { id: 'assets',       type: 'textarea', labelKey: 'assets',       placeholderKey: 'assets_ph' },
    { id: 'specs',        type: 'text',     labelKey: 'specs',        placeholderKey: 'specs_ph' },
    { id: 'theses',       type: 'textarea', labelKey: 'theses',       placeholderKey: 'theses_ph' },
    { id: 'goals',        type: 'textarea', labelKey: 'goals',        placeholderKey: 'goals_ph' },
    { id: 'audience',     type: 'textarea', labelKey: 'audience',     placeholderKey: 'audience_ph' },
    { id: 'wishes',       type: 'textarea', labelKey: 'wishes',       placeholderKey: 'wishes_ph' },
    { id: 'deadline',     type: 'text',     labelKey: 'deadline',     placeholderKey: 'deadline_ph' },
  ]
};

export default briefVideo;
